[project]
name = 'MediVerse'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.decentralized-health]
path = 'contracts/decentralized-health.clar'
clarity_version = 3
epoch = 3.1

[contracts.health-token]
path = 'contracts/health-token.clar'
clarity_version = 3
epoch = 3.1

[contracts.role-nft]
path = 'contracts/role-nft.clar'
clarity_version = 3
epoch = 3.1

[contracts.identity-nft]
path = 'contracts/identity-nft.clar'
clarity_version = 3
epoch = 3.1

[contracts.medical-record]
path = 'contracts/medical-record.clar'
clarity_version = 3
epoch = 3.1


[repl.analysis]
passes = ['check_checker']



[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
